//
//  ItemDetailScenePresenter.swift
//  TechTest
//
//  Created by user on 18/6/18.
//  Copyright (c) 2018 SM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemDetailScenePresentationLogic
{
  func presentSomething(response: ItemDetailScene.Something.Response)
}

class ItemDetailScenePresenter: ItemDetailScenePresentationLogic
{
  weak var viewController: ItemDetailSceneDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ItemDetailScene.Something.Response)
  {
    let viewModel = ItemDetailScene.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
