//
//  ItemDetailScenePresenter.swift
//  TechTest
//
//  Created by user on 18/6/18.
//  Copyright (c) 2018 SM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemDetailScenePresentationLogic
{
  func presentItemDetail(itemDetailObject: Item)
}

class ItemDetailScenePresenter: ItemDetailScenePresentationLogic
{
  weak var viewController: ItemDetailSceneDisplayLogic?
  
  // MARK: make model presentable
  
  func presentItemDetail(itemDetailObject: Item)
  {
    let viewModel = ItemDetailScene.ItemDetail.ViewModel(selectedItem: itemDetailObject)
    viewController?.displayItemDetail(viewModel: viewModel)
  }
  
}
