//
//  ItemDetailSceneInteractor.swift
//  TechTest
//
//  Created by user on 18/6/18.
//  Copyright (c) 2018 SM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemDetailSceneBusinessLogic
{
  func doSomething(request: ItemDetailScene.Something.Request)
}

protocol ItemDetailSceneDataStore
{
  //var name: String { get set }
}

class ItemDetailSceneInteractor: ItemDetailSceneBusinessLogic, ItemDetailSceneDataStore
{
  var presenter: ItemDetailScenePresentationLogic?
  var worker: ItemDetailSceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ItemDetailScene.Something.Request)
  {
    worker = ItemDetailSceneWorker()
    worker?.doSomeWork()
    
    let response = ItemDetailScene.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
