//
//  ItemDetailSceneInteractor.swift
//  TechTest
//
//  Created by user on 18/6/18.
//  Copyright (c) 2018 SM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemDetailSceneBusinessLogic
{
  func getItemDetail()
}

protocol ItemDetailSceneDataStore
{
  var selectedItem: Item? { set get }
}

class ItemDetailSceneInteractor: ItemDetailSceneBusinessLogic, ItemDetailSceneDataStore
{
  var presenter: ItemDetailScenePresentationLogic?
  var worker: ItemDetailSceneWorker?
  var selectedItem: Item?
  
  // MARK: send itemDetail Model to presenter
  func getItemDetail()
  {
    guard let item = selectedItem else { return }
    presenter?.presentItemDetail(itemDetailObject: item)
  }
  
  
}
