//
//  ItemListScenePresenter.swift
//  TechTest
//
//  Created by user on 18/6/18.
//  Copyright (c) 2018 SM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemListScenePresentationLogic
{
  func presentItemCollectionResponseModel(response: ItemListScene.ItemList.Response)
  func presentError(error: Error)
}

class ItemListScenePresenter: ItemListScenePresentationLogic
{
  weak var viewController: ItemListSceneDisplayLogic?
  
  // MARK: make view model here and dispatch to view controller
  
  func presentItemCollectionResponseModel(response: ItemListScene.ItemList.Response)
  {
    let viewModel = ItemListScene.ItemList.ViewModel(itemArray: response.responseModel.rows)
    viewController?.displayItems(viewModel: viewModel)
  }
  
  func presentError(error: Error)
  {
    viewController?.presentError(error: error)
  }
  
}
