//
//  ItemListScenePresenter.swift
//  TechTest
//
//  Created by user on 18/6/18.
//  Copyright (c) 2018 SM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemListScenePresentationLogic
{
  func presentSomething(response: ItemListScene.Something.Response)
}

class ItemListScenePresenter: ItemListScenePresentationLogic
{
  weak var viewController: ItemListSceneDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ItemListScene.Something.Response)
  {
    let viewModel = ItemListScene.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
