//
//  ItemListSceneWorker.swift
//  TechTest
//
//  Created by user on 18/6/18.
//  Copyright (c) 2018 SM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ItemListSceneWorker
{
  var loadItemListService: LoadItemProtocol
  
  init(loadItemListService: LoadItemProtocol)
  {
    self.loadItemListService = loadItemListService
  }
  
  func initiateLoadingItemCollection(withCredentials payload: ItemListScene.ItemList.Request, completionHandler: @escaping (ItemCollection?, Error?) -> Void ) {
    self.loadItemListService.loadItemListRequest(withCredentials: payload) { (responseObject, error) in
      completionHandler(responseObject, error)
    }
  }
  
}
