//
//  ItemListSceneInteractor.swift
//  TechTest
//
//  Created by user on 18/6/18.
//  Copyright (c) 2018 SM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemListSceneBusinessLogic
{
  func doSomething(request: ItemListScene.Something.Request)
  func loadItemList(request: ItemListScene.ItemList.Request)
}

protocol ItemListSceneDataStore
{
  //var name: String { get set }
}

class ItemListSceneInteractor: ItemListSceneBusinessLogic, ItemListSceneDataStore
{
  var presenter: ItemListScenePresentationLogic?
  var worker: ItemListSceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ItemListScene.Something.Request)
  {
    worker = ItemListSceneWorker()
    worker?.doSomeWork()
    
    let response = ItemListScene.Something.Response()
    presenter?.presentSomething(response: response)
  }
  
  func loadItemList(request: ItemListScene.ItemList.Request)
  {
    
  }
  
}
